[workspace]
authors = ["jollywatt <jo.alex.w@gmail.com>"]
channels = ["conda-forge"]
name = "auto-commit"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
