[workspace]
authors = ["jollywatt <jo.alex.w@gmail.com>"]
channels = ["conda-forge"]
name = "auto-commit"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
watchdog = ">=6.0.0,<7"
python-dotenv = ">=1.1.0,<2"
requests = ">=2.32.3,<3"
jj = ">=0.30.0,<0.31"
ipython = ">=9.3.0,<10"
termcolor = ">=3.1.0,<4"
websockets = ">=15.0.1,<16"
